 name: Publish NuGet Package

 on:
   push:
     branches:
       - main

 jobs:
   publish:
     runs-on: self-hosted
     name: Publish to GitHub Packages
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Restore dependencies
         run: dotnet restore
 
       - name: Build
         run: dotnet build --configuration Release /p:Version=${{ github.run_number }}
 
       - name: Pack
         run: dotnet pack --configuration Release --output ./nupkgs /p:Version=${{ github.run_number }}

       - name: Publish to GitHub Packages
         run: dotnet nuget push ./nupkgs/*.nupkg -s https://nuget.pkg.github.com/malindaushan999/index.json -k ${{ secrets.NUGET_TOKEN }}
